### ISSUE TITLE
Placehold cover image causing website page to show as Not Secure

### ISSUE THREAD

**Issue by adzpower** [xylusthemes/import-facebook-events#33]
If you don't upload a event photo, it appears blank on Facebook, but is imported as a placehold image into the website. I believe because the placehold.it website is http not https it is causing the parent website to show as Not Secure (SSL issue).

<div class="ife_event" >
<div class="img_placeholder" style=" background: url('http://placehold.it/420x150?text=September+07') no-repeat left top;"></div>

**Comment by support-xylusthemes** [comment]
Hello @adzpower ,

Thanks for reporting issue. this issue is fixed on recent release. please feel to reopen it if you still face it.

Thanks

**Comment by support-xylusthemes** [comment]
Hello @adzpower ,

Thanks for reporting issue. this issue is fixed on recent release. please feel to reopen it if you still face it.

Thanks
